### ISSUE TITLE
Publish to MyGet failure

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#3024]
Currently it's not possible to push new nuget packages

https://github.com/neo-project/neo/actions/runs/7183650804/job/19563025824

**Comment by cschuchardt88** [comment]
I think we can split up into different steps (each package) that may fix the problem.... No way to test it? without Merge?

**Comment by shargon** [comment]
> I think we can split up into different steps (each package) that may fix the problem.... No way to test it? without Merge?

I was thinking in the same, multiple pushes

**Comment by cschuchardt88** [comment]
Im making fix right now, testing...

**Comment by cschuchardt88** [comment]
The package is too large according to your subscription quota. Please verify before asking support as you can often simply resolve it by upgrading your subscription plan or adjusting retention policies on your feed to free up some space. [Check this "Storage Quota Exceeded" KB article for more details](https://myget.freshdesk.com/support/solutions/articles/19000054560-storage-quota-exceeded).
The total size of the packages that are pending upload (through the web UI) is too large.
The package is simply too large (as in Gb's of size) and our servers reject it.

**Comment by superboyiii** [comment]
@shargon @cschuchardt88 Please try again. Should be OK now. Reserved limit is fixed to only 20 packages.

**Comment by shargon** [comment]
> @shargon @cschuchardt88 Please try again. Should be OK now. Reserved limit is fixed to only 20 packages.

https://github.com/neo-project/neo/actions/runs/7200435032/job/19630444523

The error remains

**Comment by superboyiii** [comment]
> https://github.com/neo-project/neo/actions/runs/7200435032/job/19630444523
> 
> The error remains

Should not be a space rest issue.
<img width="121" alt="7e1792e7f26712f4627ad23c7a3f486" src="https://github.com/neo-project/neo/assets/38493437/496b7a98-fe90-4120-86f4-f09357335410">
@cschuchardt88 Any other idea?

**Comment by superboyiii** [comment]
Something must wrong here... I tried to pack Neo locally, but only cost little space....
![26dc98bf19997094328bb993f83b1f1](https://github.com/neo-project/neo/assets/38493437/fb31b9ab-89e9-4a8e-9387-df9e674095e5)

**Comment by superboyiii** [comment]
@cschuchardt88 Any idea?

**Comment by cschuchardt88** [comment]
Could be It tries to add the symbols at same time. Maybe remove the symbols for now and try again. I think it's the symbol server could you check that?

**Comment by shargon** [comment]
> Something must wrong here... I tried to pack Neo locally, but only cost little space.... Even add neo-express, it should not be so large... ![26dc98bf19997094328bb993f83b1f1](https://private-user-images.githubusercontent.com/38493437/290466610-fb31b9ab-89e9-4a8e-9387-df9e674095e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjM5MjIsIm5iZiI6MTcwMjU2MzYyMiwicGF0aCI6Ii8zODQ5MzQzNy8yOTA0NjY2MTAtZmIzMWI5YWItODllOS00YThlLTkzODctZGY5ZTY3NDA5NWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE0MjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNDE2NTVmYzZmZTRjYjA5NmMxNjY0NWZkZmViYmE4N2ExZDEzN2ZjM2FhNzdlMmIxYThhNGZlMDc4OGM5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKALxy5O8JmvJqeMIrylbgXhytxsrWlhcrTMZ_rx5XE)

With symbols?

**Comment by shargon** [comment]
> Could be It tries to add the symbols at same time. Maybe remove the symbols for now and try again. I think it's the symbol server could you check that?

Is good for me if it works

**Comment by cschuchardt88** [comment]
I see the problem, fixing now....

**Comment by cschuchardt88** [comment]
See #3029

**Comment by cschuchardt88** [comment]
We going to make contract support for `myget` to see that the problem is.

**Comment by shargon** [comment]
Is something in the nuget account, because now is happening in dev-pack without any change

**Comment by cschuchardt88** [comment]
You sure it's not the buffering of multiple files? I have a free `myget` account and I found out that if you added flag `--disable-buffering` it goes away.

**Comment by cschuchardt88** [comment]
## These my settings and works fine.
![image](https://github.com/neo-project/neo/assets/8141309/38a950ab-5b66-4f63-965f-c9ad07e2700b)
![image](https://github.com/neo-project/neo/assets/8141309/b5390886-7eb1-4245-9000-5bd5241b7630)

**Comment by shargon** [comment]
@superboyiii do you have access to the nuget account?

**Comment by cschuchardt88** [comment]
Are we not using `myget` anymore? Can we remove from workflow?

**Comment by shargon** [comment]
> Are we not using `myget` anymore? Can we remove from workflow?

Yes, but what we will use?

**Comment by cschuchardt88** [comment]
Its mono-repo, shouldn't need anything. But we can publish to `Github` `packages` If you really need it.

**Comment by shargon** [comment]
> Its mono-repo, shouldn't need anything. But we can publish to `Github` `packages` If you really need it.
> 
> Havent been updated in 4 years https://github.com/neo-project/neo/pkgs/nuget/Neo

Ok, let's start commenting myget in the workflow, and we will see in the future if we need it, now it's worthless

**Comment by shargon** [comment]
Fixed, currently we push to github and myGet. Maybe we should review releases.
