### ISSUE TITLE
Innormal exception displays sometimes while restart neo-cli.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#570]
When using exit command or neo-cli sever was killed by linux system, if restart neo-cli again, "segement fault" is often shown on the window. It makes neo-cli have to restart for several times to run normally.

**Comment by jsolman** [comment]
I’m expecting to work on improving the shutdown process very soon.

**Comment by jsolman** [comment]
This is fixed by #574 
I didn't see any issues on exit when running neo-cli when including those changes.

**Comment by superboyiii** [comment]
Awesome! Good job!

**Comment by jsolman** [comment]
Turns out we went with Erik's solution from #595 for this.
It still will give some messages from actors being terminated, but it shouldn't segmentation fault.
We can leave this open to ensure it is fixed on the next release.

**Comment by jsolman** [comment]
This should be fixed by #607

**Comment by shargon** [comment]
@superboyiii could you check if is solved?

**Comment by superboyiii** [comment]
@jsolman @shargon Seems still exist. This time restarting isn't able to help.
![image](https://user-images.githubusercontent.com/38493437/54898268-8c138b80-4f06-11e9-8ce9-4c441ea9dca1.png)

**Comment by superboyiii** [comment]
I found it could appear when restarting after using [exit] command in neo-cli. Seems the OnStop() function for exiting neo-cli is not a safe way.

**Comment by superboyiii** [comment]
@shargon Haven't met this issue on neo-cli-2.10.0 till now.

**Comment by shargon** [comment]
I will close it, if you find it again, please reopen it :)

**Comment by superboyiii** [comment]
@shargon  Unluckly, face it again.
![image](https://user-images.githubusercontent.com/38493437/55055042-d62e7580-509c-11e9-8a99-1590e6c26422.png)

**Comment by superboyiii** [comment]
It seems likely appear after using [exit] command on neo-cli and then make restarting.

**Comment by superboyiii** [comment]
The worst situation could be always "Segmentation fault" and neo-cli isn't able to be restart again.

**Comment by jsolman** [comment]
Need to try with 2.10.1 and the new import blocks plugin if it is happening to you during import blocks.

**Comment by superboyiii** [comment]
@jsolman Fine. I will.
